spring.application.name=Tugas_CRUD_20230140064
spring.datasource.url=jdbc:mysql://localhost:3309/spring_ktp
spring.datasource.username=root
spring.datasource.password=mFw12305

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true